In [ ]:
#This code is used to align the 2 images features 

from __future__ import print_function
import cv2
import numpy as np
 
MAX_FEATURES = 450
GOOD_MATCH_PERCENT = 0.15
 
def alignImages(im1, im2):
 
  # Convert images to grayscale
    im1Gray = cv2.cvtColor(im1, cv2.COLOR_BGR2GRAY)
    im2Gray = cv2.cvtColor(im2, cv2.COLOR_BGR2GRAY)
   
  # Detect ORB features and compute descriptors.
    orb = cv2.ORB_create(MAX_FEATURES)
    keypoints1, descriptors1 = orb.detectAndCompute(im1Gray, None)
    keypoints2, descriptors2 = orb.detectAndCompute(im2Gray, None)
   
  # Match features.
    matcher = cv2.DescriptorMatcher_create(cv2.DESCRIPTOR_MATCHER_BRUTEFORCE_HAMMING)
    matches = matcher.match(descriptors1, descriptors2, None)
   
  # Sort matches by score
    matches.sort(key=lambda x: x.distance, reverse=False)
 
  # Remove not so good matches
    numGoodMatches = int(len(matches) * GOOD_MATCH_PERCENT)
    matches = matches[:numGoodMatches]
 
  # Draw top matches
    imMatches = cv2.drawMatches(im1, keypoints1, im2, keypoints2, matches, None)
    cv2.imwrite("matches.jpg", imMatches)
    #cv2.imshow("matches.jpg", imMatches)
  # Extract location of good matches
    points1 = np.zeros((len(matches), 2), dtype=np.float32)
    points2 = np.zeros((len(matches), 2), dtype=np.float32)
 
    for i, match in enumerate(matches):
        points1[i, :] = keypoints1[match.queryIdx].pt
        points2[i, :] = keypoints2[match.trainIdx].pt
   
  # Find homography
    h, mask = cv2.findHomography(points1, points2, cv2.RANSAC)
 
  # Use homography
    height, width, channels = im2.shape
    im1Reg = cv2.warpPerspective(im1, h, (width, height))
   
    return im1Reg, h
 
 
if __name__ == '__main__':
   
  # Read reference image
    refFilename = "C:/Users/CG-DTE/Downloads/Mtech 1st sem reference books/M.Tech project/Results/data(Total n_frames)/frame19.jpg"
    #print("Reading reference image : ", refFilename)
    imReference = cv2.imread(refFilename, cv2.IMREAD_COLOR)
 
  # Read image to be aligned
    imFilename = "C:/Users/CG-DTE/Downloads/Mtech 1st sem reference books/M.Tech project/Results/data(Total n_frames)/frame20.jpg"
    #print("Reading image to align : ", imFilename);  
    im = cv2.imread(imFilename, cv2.IMREAD_COLOR)
   
    print("Aligning images ...")
  # Registered image will be resotred in imReg. 
  # The estimated homography will be stored in h. 
    imReg, h = alignImages(im, imReference)
   
  # Write aligned image to disk. 
    outFilename = "C:/Users/CG-DTE/Downloads/Mtech 1st sem reference books/M.Tech project/Results/data_consecutive_out/Frame19.jpg"
    #print("Saving aligned image : ", outFilename); 
    cv2.imwrite(outFilename, imReg)
    #cv2.imshow("1",imReg)
    cv2.waitKey(0)
 
  # Print estimated homography
#print("Estimated homography : \n",  h)

In [ ]:
#This code is used to align the images in a video :(getting error)

import numpy as np
import cv2

cap = cv2.VideoCapture("C:/Users/CG-DTE/Downloads/Mtech 1st sem reference books/M.Tech project/Original_video.avi")
print("capture= ",cap)
      
n_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
print("n_frames= ",n_frames)

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) 
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

print("width= ", width)
print("height= ", height)


fps = cap.get(cv2.CAP_PROP_FPS)
print("fps= ",fps)

fourcc = cv2.VideoWriter_fourcc(*'XVID')
print("Fourcc= ",fourcc)

MAX_FEATURES = 200
GOOD_MATCH_PERCENT = 0.15


for i in range(0,1936):
    ret,prev_frame=cap.read()
    prev_gray=cv2.cvtColor(prev_frame,cv2.COLOR_BGR2GRAY)
    orb = cv2.ORB_create(MAX_FEATURES)
    keypoints1, descriptors1 = orb.detectAndCompute(prev_gray, None)
    for j in range(1,1937):
        succ, curr_frame = cap.read()
        curr_gray=cv2.cvtColor(curr_frame,cv2.COLOR_BGR2GRAY)
        keypoints2, descriptors2 = orb.detectAndCompute(curr_gray, None)
        matcher = cv2.DescriptorMatcher_create(cv2.DESCRIPTOR_MATCHER_BRUTEFORCE_HAMMING)
        matches = matcher.match(descriptors1, descriptors2, None)
        matches.sort(key=lambda x: x.distance, reverse=False)
        numGoodMatches = int(len(matches) * GOOD_MATCH_PERCENT)
        matches = matches[:numGoodMatches]
        frame_Matches = cv2.drawMatches(prev_frame, keypoints1, curr_frame, keypoints2, matches, None)
        #cv2.imwrite("matches.jpg", frame_Matches)
        cv2.imshow("matches.jpg",  frame_Matches)
        points1 = np.zeros((len(matches), 2), dtype=np.float32)
        points2 = np.zeros((len(matches), 2), dtype=np.float32)
        for z, match in enumerate(matches):
            points1[z, :] = keypoints1[match.queryIdx].pt
            #print(points1[z, :])
            points2[z, :] = keypoints2[match.trainIdx].pt
            #print(points2[z, :])
        h, mask = cv2.findHomography(points1, points2, cv2.RANSAC)
        print("h= ",h)
        height, width, channels = curr_frame.shape
        print(curr_frame.shape)
        frame_Reg = cv2.warpPerspective(prev_frame, h, (width, height))
        cv2.imshow("frame_out",frame_Reg)
if cv2.waitKey(1) & 0xFF==ord("q"):
            break
   
 
cap.release()
#out.release()
cv2.destroyAllWindows()      
        
    


In [ ]:
#Basic code to implement hough transform on a image
import cv2
import numpy as np


cap=cv2.VideoCapture("C:/Users/CG-DTE/Downloads/Mtech 1st sem reference books/M.Tech project/Results/cropped_video.avi")
fourcc = cv2.VideoWriter_fourcc(*'XVID')
#print("Fourcc= ",fourcc)
fps=4.0
#n_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
#print("n_frames= ",n_frames)

#out = cv2.VideoWriter('Hough_line_video.avi',fourcc, fps, (1280, 720),True)
#print("Ouput= ",out)
while(True):
    ret,frame=cap.read()
    #frame = cv2.imread("C:/Users/CG-DTE/Downloads/Mtech 1st sem reference books/M.Tech project/Results/data_out/Frame1.jpg")
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray,50,150,apertureSize = 3)

    lines = cv2.HoughLines(edges,1,np.pi/180,20)
    for rho,theta in lines[0]:
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a*rho
        y0 = b*rho
        x1 = int(x0 + 1000*(-b))
        y1 = int(y0 + 1000*(a))
        x2 = int(x0 - 1000*(-b))
        y2 = int(y0 - 1000*(a))
    cv2.line(frame,(390,240),(390,500),(0,255,0),2)
    #cv2.line(frame,(640,460),(640,720),(0,0,255),2)
    cv2.imshow("line",frame)
    #out.write(frame)
    #cv2.line(img,(480,460),(480,720),(0,0,255),2)
    #cv2.line(img,(780,460),(780,720),(0,0,255),2)
    if cv2.waitKey(1) & 0xFF==ord("q"):
            break
cap.release()
out.release()
cv2.destroyAllWindows()
    
    
#cv2.imwrite("C:/Users/CG-DTE/Downloads/Mtech 1st sem reference books/M.Tech project/Results/Hough_lines_data_out/Frame2.jpg",img)

In [ ]:
# This code is used to reconstruct the video using the frames
import cv2
import numpy as np
import glob
 
img_array = []
for filename in glob.glob("C:/Users/CG-DTE/Downloads/Mtech 1st sem reference books/M.Tech project/Results/data_consecutive_out/*.jpg"):
    img = cv2.imread(filename)
    height, width, layers = img.shape
    size = (width,height)
    img_array.append(img)
 
 
out = cv2.VideoWriter("C:/Users/CG-DTE/Downloads/Mtech 1st sem reference books/M.Tech project/Results/data_consecutive_out/video.avi",cv2.VideoWriter_fourcc(*'XVID'), 2, (1280,720))
 
for i in range(len(img_array)):
    out.write(img_array[i])
out.release()

In [ ]:
#CODE to crop a video
import numpy as np
import cv2

cap=cv2.VideoCapture("C:/Users/CG-DTE/Downloads/Mtech 1st sem reference books/M.Tech project/Results/data_out/video.avi")
fourcc = cv2.VideoWriter_fourcc(*'XVID')
print("Fourcc= ",fourcc)
fps=4.0

out = cv2.VideoWriter('Align&crop_video.avi',fourcc, fps, (780, 500),True)
print("Ouput= ",out)
while(True):
    ret,frame=cap.read()
    cropped=frame[100:600,220:1000]
    print(cropped.size)
    print(cropped.shape)
    cv2.imshow("cropped",cropped)
    out.write(cropped)
    if cv2.waitKey(1) & 0xFF==ord("q"):
            break
cap.release()
out.release()
cv2.destroyAllWindows()

In [1]:
#Code of applying Hough Transform on a video

import cv2
import numpy as np
cap=cv2.VideoCapture("C:/Users/CG-DTE/Downloads/Mtech 1st sem reference books/M.Tech project/Original_video.avi")
fourcc = cv2.VideoWriter_fourcc(*'XVID')
print("Fourcc= ",fourcc)
fps=30.0
out = cv2.VideoWriter('Tracking_Railway_lines_Original_video.avi',fourcc, fps, (1280, 720),True)
while(True):
    ret,frame=cap.read()
    hsv=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    frame1=cv2.GaussianBlur(hsv,(21,21),0,0)
    cv2.imshow("hsv",hsv)
    low_pink=np.array([50, 104, 144])
    up_pink=np.array([180,  255, 255 ])
    
    Mask=cv2.inRange(frame,low_pink,up_pink)
    #res=cv2.bitwise_and(frame,frame,Mask)
    edges=cv2.Canny(Mask,75,150)
    lines=cv2.HoughLinesP(edges,1,np.pi/180,20)
    
    if lines is not None:
        for line in lines:
            x1,y1,x2,y2=line[0]
            cv2.line(frame,(x1,y1),(x2,y2),(0,255,0),2)
    print(lines)
    cv2.imshow("mask",Mask)
    #cv2.imshow("res",res)
    cv2.imshow("frame",frame)
    out.write(frame)
    if cv2.waitKey(1) & 0xFF==ord("q"):
            break
cap.release()
out.release()
cv2.destroyAllWindows()
    

Fourcc=  1145656920
[[[ 531  576  531  575]]

 [[ 643  231  643  230]]

 [[ 744  473  744  473]]

 ...

 [[  84  236   84  236]]

 [[1143  331 1143  331]]

 [[ 919   21  919   21]]]
[[[ 752  515  752  517]]

 [[ 759  504  759  506]]

 [[ 722  358  722  359]]

 ...

 [[1228  238 1229  238]]

 [[  81  432   81  432]]

 [[ 105  470  105  470]]]
[[[ 716  285  716  285]]

 [[ 653  485  657  485]]

 [[  87  327   88  327]]

 ...

 [[1179  531 1181  530]]

 [[1126  619 1128  619]]

 [[ 937  369  938  369]]]
[[[ 382  307  385  305]]

 [[ 264  378  265  377]]

 [[ 247  388  247  388]]

 ...

 [[1087  603 1087  603]]

 [[ 402  635  402  635]]

 [[ 638  583  638  583]]]
[[[ 380  289  380  289]]

 [[ 363  367  363  367]]

 [[  10  663   13  660]]

 ...

 [[1134  613 1134  613]]

 [[1142  549 1142  549]]

 [[ 691  325  691  325]]]
[[[  87  589   89  587]]

 [[1124  556 1124  556]]

 [[ 577  627  583  627]]

 ...

 [[ 424  703  425  703]]

 [[1011  208 1011  208]]

 [[ 872  101  873  101]]]
[[[728  

[[[ 745  103  763  103]]

 [[  93   24  119   24]]

 [[ 854  100  854  100]]

 ...

 [[ 591  572  591  572]]

 [[ 449  120  449  120]]

 [[1068   79 1068   77]]]
[[[ 752  298  752  300]]

 [[ 797  491  797  492]]

 [[ 795  482  795  484]]

 ...

 [[1187  508 1187  508]]

 [[ 340  106  340  106]]

 [[ 871   69  871   69]]]
[[[ 356   89  357   89]]

 [[ 601   88  611   88]]

 [[ 913   78  921   78]]

 ...

 [[1191  688 1192  688]]

 [[ 770  448  770  447]]

 [[ 144  436  144  436]]]
[[[ 754   16  767   16]]

 [[ 739  100  741  100]]

 [[ 593  115  598  115]]

 ...

 [[1134  123 1134  123]]

 [[ 740  484  740  485]]

 [[ 300  121  301  121]]]
[[[ 111   39  137   39]]

 [[ 750  638  750  640]]

 [[   3  648    4  647]]

 ...

 [[ 820  115  820  115]]

 [[1269  195 1269  193]]

 [[1118  705 1118  705]]]
[[[ 756  592  756  594]]

 [[ 155  129  155  129]]

 [[ 779  692  779  694]]

 ...

 [[1061  711 1061  711]]

 [[1131  472 1132  473]]

 [[ 407  121  408  121]]]
[[[ 882   76  899   76]]

 [

[[[ 727  134  749  134]]

 [[ 273   51  273   51]]

 [[ 674   38  687   38]]

 ...

 [[ 618  357  618  357]]

 [[ 852  189  852  189]]

 [[1255  637 1256  637]]]
[[[329  32 332  32]]

 [[218  32 247  32]]

 [[291 157 291 157]]

 ...

 [[565 171 565 171]]

 [[551 119 551 119]]

 [[793 190 793 190]]]
[[[ 763   32  765   32]]

 [[ 705  479  705  481]]

 [[   8   45   20   45]]

 ...

 [[1177  627 1177  627]]

 [[  15  526   15  526]]

 [[ 721  531  721  532]]]
[[[ 618   24  618   24]]

 [[ 555   27  569   27]]

 [[ 701  472  701  472]]

 ...

 [[1266  589 1266  589]]

 [[1221  106 1221  105]]

 [[ 984  673  985  673]]]
[[[ 221   54  221   54]]

 [[ 556  133  571  133]]

 [[ 540   43  552   43]]

 ...

 [[ 558   52  558   52]]

 [[  59   43   59   43]]

 [[1191  582 1191  581]]]
[[[ 862  120  882  120]]

 [[  79   39   93   39]]

 [[ 567  516  567  515]]

 ...

 [[  15  450   15  450]]

 [[ 613  372  613  371]]

 [[1211  621 1212  622]]]
[[[ 397  132  414  132]]

 [[ 397   21  413   21]]



[[[ 735  548  735  550]]

 [[  76   28   92   28]]

 [[1270   92 1270   92]]

 ...

 [[ 527  351  527  351]]

 [[ 383  126  384  126]]

 [[ 895  150  895  149]]]
[[[ 845  106  845  106]]

 [[ 552  116  556  116]]

 [[ 456  124  470  124]]

 ...

 [[ 785   12  785   12]]

 [[1058  717 1058  716]]

 [[ 723  161  723  161]]]
[[[ 709  115  733  115]]

 [[ 518  129  520  129]]

 [[ 511  119  529  119]]

 ...

 [[1115  659 1115  659]]

 [[ 613  404  613  404]]

 [[1168  129 1168  129]]]
[[[863 107 886 107]]

 [[427  16 441  16]]

 [[502  18 513  18]]

 ...

 [[422 171 424 171]]

 [[404 342 404 342]]

 [[527 681 527 679]]]
[[[ 719  467  719  469]]

 [[ 568  117  584  117]]

 [[ 757  108  773  108]]

 ...

 [[1023  150 1023  150]]

 [[1109  106 1109  107]]

 [[ 906   86  906   86]]]
[[[719 116 740 115]]

 [[802 133 809 133]]

 [[714 434 714 436]]

 ...

 [[972  66 972  66]]

 [[123 682 123 682]]

 [[697  76 699  78]]]
[[[757  99 773  99]]

 [[719 102 721 102]]

 [[514 110 525 110]]

 ...

 [[5

[[[ 979  156  979  156]]

 [[1270  125 1271  125]]

 [[ 438  156  441  156]]

 ...

 [[ 724  121  724  121]]

 [[ 901  233  901  233]]

 [[1012  154 1012  154]]]
[[[758 154 760 154]]

 [[570  15 598  15]]

 [[907 140 907 140]]

 ...

 [[556 184 558 184]]

 [[996 169 996 169]]

 [[730 508 730 508]]]
[[[ 817  139  832  139]]

 [[ 580  157  592  157]]

 [[ 621  158  629  158]]

 ...

 [[1059  498 1059  498]]

 [[ 122   21  123   21]]

 [[1187  677 1187  677]]]
[[[377 150 380 150]]

 [[432 148 435 148]]

 [[780 135 780 135]]

 ...

 [[137 195 137 195]]

 [[711 395 711 395]]

 [[253 126 253 129]]]
[[[ 264   33  287   33]]

 [[ 252   32  256   32]]

 [[   5   37   14   37]]

 ...

 [[ 529   33  529   33]]

 [[1126  179 1127  179]]

 [[ 872  368  872  368]]]
[[[665   7 678   7]]

 [[749 148 758 148]]

 [[266 166 267 166]]

 ...

 [[546 176 546 176]]

 [[155 454 155 454]]

 [[163 585 164 584]]]
[[[ 482    9  499    9]]

 [[ 560    8  597    8]]

 [[  63   41   74   41]]

 ...

 [[  30   21   3

[[[799 152 804 152]]

 [[270  28 281  28]]

 [[247  26 249  26]]

 ...

 [[782 222 783 222]]

 [[324 592 324 592]]

 [[821 183 822 183]]]
[[[799  32 800  32]]

 [[533  25 534  25]]

 [[301  31 317  31]]

 ...

 [[741 153 742 153]]

 [[534  87 535  88]]

 [[607 496 607 496]]]
[[[ 693  384  693  385]]

 [[ 659  225  659  227]]

 [[ 703   19  726   19]]

 ...

 [[1024  178 1024  178]]

 [[ 792  219  792  219]]

 [[ 168  600  168  600]]]
[[[540 170 546 170]]

 [[977  14 977  14]]

 [[583 160 598 160]]

 ...

 [[353 413 353 413]]

 [[113 175 121 175]]

 [[716 218 716 218]]]
[[[ 419   22  435   22]]

 [[ 137  623  138  622]]

 [[ 133  626  133  626]]

 ...

 [[ 515  200  517  200]]

 [[ 779  242  779  242]]

 [[1055  492 1055  492]]]
[[[653  23 653  23]]

 [[ 56  33  87  33]]

 [[743 157 752 157]]

 ...

 [[828  25 828  20]]

 [[129 222 130 222]]

 [[356 187 356 187]]]
[[[119  40 121  40]]

 [[552  21 567  21]]

 [[271  11 285  11]]

 ...

 [[647 361 647 361]]

 [[752 672 752 669]]

 [[661  

[[[374 193 376 193]]

 [[393 192 398 192]]

 [[663 183 668 183]]

 ...

 [[394 479 394 479]]

 [[ 56 581  59 579]]

 [[ 77  83  77  83]]]
[[[489 422 490 421]]

 [[408 182 424 182]]

 [[345  17 365  17]]

 ...

 [[513 177 513 177]]

 [[288 204 289 204]]

 [[372 184 375 184]]]
[[[ 89  28 105  28]]

 [[747 181 751 181]]

 [[ 47  28  47  28]]

 ...

 [[ 90   2  96   2]]

 [[864 167 865 167]]

 [[862 171 862 171]]]
[[[593 237 595 237]]

 [[334 526 334 526]]

 [[ 15  25  20  25]]

 ...

 [[648 189 648 189]]

 [[739 573 739 576]]

 [[844  27 844  27]]]
[[[721   1 727   1]]

 [[725 536 725 537]]

 [[685  10 698  10]]

 ...

 [[777 160 778 161]]

 [[669 254 671 254]]

 [[518 124 518 124]]]
[[[ 684    5  699    5]]

 [[ 786  170  790  170]]

 [[ 684    7  699    7]]

 ...

 [[1052  690 1052  690]]

 [[ 880  249  880  249]]

 [[1186  616 1187  617]]]
[[[ 724  166  735  166]]

 [[   3   26   18   26]]

 [[ 301   16  315   16]]

 ...

 [[ 481  191  481  191]]

 [[ 699  135  699  135]]

 [[1204  531

[[[ 864  163  865  163]]

 [[ 717  168  726  168]]

 [[ 623  488  623  487]]

 ...

 [[1012  205 1012  205]]

 [[  38  547   38  547]]

 [[ 881  102  881  104]]]
[[[656 154 662 154]]

 [[825 142 825 142]]

 [[358 166 376 166]]

 ...

 [[455 228 455 228]]

 [[ 11 236  11 236]]

 [[484  83 485  83]]]
[[[456 167 460 167]]

 [[616 556 616 555]]

 [[519 151 529 151]]

 ...

 [[820 217 820 217]]

 [[765 230 767 230]]

 [[516 214 517 214]]]
[[[652 157 652 157]]

 [[285 176 291 176]]

 [[800 153 819 153]]

 ...

 [[756 535 756 535]]

 [[918 171 920 170]]

 [[621 150 621 151]]]
[[[931 145 934 145]]

 [[155 176 155 176]]

 [[783 143 786 143]]

 ...

 [[821 386 823 386]]

 [[897 147 901 146]]

 [[886 213 886 213]]]
[[[504 157 510 157]]

 [[630 525 630 524]]

 [[787 157 797 157]]

 ...

 [[355 167 356 166]]

 [[808 245 809 245]]

 [[863 241 864 241]]]
[[[ 737  144  755  144]]

 [[ 648  153  668  153]]

 [[ 281  189  283  189]]

 ...

 [[ 291  182  291  182]]

 [[1035  217 1035  217]]

 [[  43  246

[[[553 168 558 168]]

 [[634 153 636 153]]

 [[573 165 573 165]]

 ...

 [[ 46 500  46 500]]

 [[851 253 851 253]]

 [[102 674 104 673]]]
[[[ 811  157  819  157]]

 [[ 656  149  665  149]]

 [[1034  147 1034  147]]

 ...

 [[ 478  488  478  488]]

 [[ 996  236  996  236]]

 [[ 174  630  174  630]]]
[[[ 522  170  522  170]]

 [[ 375  180  385  180]]

 [[ 414  160  425  160]]

 ...

 [[1244  543 1245  544]]

 [[1075  482 1075  482]]

 [[ 709  208  710  208]]]
[[[ 371  159  377  159]]

 [[ 651  157  663  157]]

 [[ 661  146  662  146]]

 ...

 [[1000  107 1000  111]]

 [[ 253   21  253   24]]

 [[ 873  106  873  106]]]
[[[396 177 406 177]]

 [[618 155 618 155]]

 [[432 177 445 176]]

 ...

 [[919 114 919 114]]

 [[672  63 672  63]]

 [[723 148 723 148]]]
[[[ 356  180  356  180]]

 [[ 648  164  655  164]]

 [[ 831  186  841  186]]

 ...

 [[1261  647 1261  647]]

 [[ 621  535  621  535]]

 [[ 674  156  674  156]]]
[[[998 127 998 127]]

 [[694 156 705 156]]

 [[500 213 500 213]]

 ...

 [[8

[[[1013  115 1015  115]]

 [[ 748  540  748  542]]

 [[ 724  130  727  130]]

 ...

 [[ 898  436  898  436]]

 [[ 750  526  750  526]]

 [[ 705  198  706  198]]]
[[[510 139 524 139]]

 [[496 156 500 156]]

 [[590 151 598 151]]

 ...

 [[337 243 338 244]]

 [[848 124 849 124]]

 [[732 189 732 189]]]
[[[497 158 498 158]]

 [[879 138 888 138]]

 [[569 157 577 157]]

 ...

 [[350 239 353 239]]

 [[719 214 719 214]]

 [[724 182 724 182]]]
[[[827 144 827 144]]

 [[565 158 565 158]]

 [[262 174 262 174]]

 ...

 [[296 189 296 187]]

 [[ 88  34  92  34]]

 [[471 167 473 168]]]
[[[ 446  163  449  163]]

 [[ 517  159  522  159]]

 [[ 671  150  687  149]]

 ...

 [[1039  211 1039  211]]

 [[ 860  252  860  252]]

 [[1008  175 1008  175]]]
[[[ 862  141  863  141]]

 [[ 422  164  431  164]]

 [[ 378  169  392  169]]

 ...

 [[1001  127 1002  127]]

 [[1001  159 1001  159]]

 [[ 759  255  759  255]]]
[[[ 106  170  106  170]]

 [[ 375  155  390  155]]

 [[ 145  220  148  220]]

 ...

 [[ 134  176  13

[[[465 108 470 108]]

 [[341 116 355 116]]

 [[120 141 120 141]]

 ...

 [[727 181 727 181]]

 [[599 593 600 590]]

 [[379 165 379 165]]]
[[[ 683   96  684   96]]

 [[ 571  102  584  102]]

 [[ 512  116  516  116]]

 ...

 [[1139  281 1139  281]]

 [[ 626  486  626  486]]

 [[  89  655   89  655]]]
[[[ 518  115  524  115]]

 [[ 627   94  636   94]]

 [[ 130  136  132  136]]

 ...

 [[ 923  133  924  132]]

 [[ 145  605  145  605]]

 [[1011   82 1011   82]]]
[[[690 102 692 102]]

 [[282 123 290 123]]

 [[349 125 360 125]]

 ...

 [[609 201 609 201]]

 [[637  92 641  92]]

 [[752 227 753 226]]]
[[[752  85 761  85]]

 [[433 100 447  99]]

 [[402 119 411 119]]

 ...

 [[889 219 889 219]]

 [[931  74 935  74]]

 [[731 200 731 200]]]
[[[1048   71 1048   71]]

 [[ 395  105  405  105]]

 [[ 889   78  900   78]]

 ...

 [[1111  112 1111  112]]

 [[ 175  180  175  180]]

 [[1007  638 1007  638]]]
[[[415 107 424 107]]

 [[602 555 602 554]]

 [[118 122 118 122]]

 ...

 [[362 364 364 364]]

 [[913

[[[ 445   85  454   85]]

 [[ 275   93  280   93]]

 [[ 292  108  314  108]]

 ...

 [[ 811  215  811  215]]

 [[ 187  422  187  422]]

 [[1236  559 1236  559]]]
[[[831  84 845  84]]

 [[392 105 399 105]]

 [[470  83 470  83]]

 ...

 [[638 184 640 182]]

 [[ 43 670  44 670]]

 [[160 133 160 133]]]
[[[1022   62 1039   62]]

 [[ 771   69  788   69]]

 [[ 603   92  606   92]]

 ...

 [[ 844   68  847   67]]

 [[1124  514 1124  514]]

 [[ 120  172  120  172]]]
[[[ 398   87  412   87]]

 [[1130   79 1134   79]]

 [[1116   77 1125   77]]

 ...

 [[  47  558   48  558]]

 [[ 348  374  348  374]]

 [[ 395  457  396  456]]]
[[[269  99 274  99]]

 [[568  86 579  86]]

 [[666  99 677  99]]

 ...

 [[ 92 547  92 547]]

 [[517 201 517 201]]

 [[619 530 619 530]]]
[[[ 433  109  453  109]]

 [[ 420   96  422   96]]

 [[1234   83 1234   83]]

 ...

 [[ 251   30  251   30]]

 [[ 480  190  480  190]]

 [[1044  343 1045  344]]]
[[[ 829   94  829   94]]

 [[ 671  100  672  100]]

 [[ 548   88  552   88]]

[[[ 842   42  857   42]]

 [[ 868   43  886   43]]

 [[ 285   67  296   67]]

 ...

 [[1225  579 1225  579]]

 [[ 524  172  524  172]]

 [[ 637  404  637  403]]]
[[[1069   55 1082   55]]

 [[ 342   61  359   61]]

 [[ 376   62  377   62]]

 ...

 [[ 279  176  281  176]]

 [[ 770  159  770  160]]

 [[1002   41 1002   41]]]
[[[ 420   55  437   55]]

 [[ 747  222  747  222]]

 [[  56  653   61  650]]

 ...

 [[ 728  144  728  144]]

 [[ 521  191  522  191]]

 [[1034  440 1034  440]]]
[[[ 652   69  667   69]]

 [[ 589   70  598   70]]

 [[ 764  650  764  652]]

 ...

 [[1111  181 1113  181]]

 [[ 256   76  256   74]]

 [[ 510  416  510  416]]]
[[[688  49 697  49]]

 [[441  78 456  78]]

 [[723  50 735  50]]

 ...

 [[758 216 758 216]]

 [[871 225 872 225]]

 [[875  58 877  58]]]
[[[1134   50 1139   50]]

 [[ 557  644  560  633]]

 [[ 704   66  713   66]]

 ...

 [[ 772   90  772   90]]

 [[ 630  159  630  159]]

 [[1178  560 1178  560]]]
[[[1075   52 1092   52]]

 [[1120   31 1122   31]]



[[[ 269   53  287   53]]

 [[1014   28 1030   28]]

 [[ 147   62  147   62]]

 ...

 [[ 114  169  114  169]]

 [[ 702   21  702   21]]

 [[ 652  368  653  368]]]
[[[ 428   25  442   25]]

 [[ 283   53  298   53]]

 [[1077  149 1077  149]]

 ...

 [[ 732  499  732  499]]

 [[1268  603 1269  604]]

 [[ 555   27  555   27]]]
[[[837  11 863  11]]

 [[663  44 674  44]]

 [[734  42 750  42]]

 ...

 [[541  39 541  39]]

 [[ 83 518  85 518]]

 [[979 546 979 546]]]
[[[290  33 301  33]]

 [[732  42 748  42]]

 [[630  23 640  23]]

 ...

 [[580 562 580 561]]

 [[ 95 506  98 505]]

 [[404 129 404 129]]]
[[[ 319   51  337   51]]

 [[ 502   17  516   17]]

 [[ 488   40  500   40]]

 ...

 [[ 586  186  586  186]]

 [[1243  694 1243  694]]

 [[1084  140 1084  139]]]
[[[ 451   27  460   27]]

 [[1131    6 1131    6]]

 [[ 759   19  759   19]]

 ...

 [[1111  524 1112  524]]

 [[ 751  200  751  200]]

 [[ 150  145  150  145]]]
[[[1034    8 1050    8]]

 [[ 908   30  919   30]]

 [[ 120   57  133   57]]

[[[ 648    4  667    4]]

 [[ 382  154  387  154]]

 [[1006  192 1007  192]]

 ...

 [[ 876  462  876  462]]

 [[1072  209 1072  209]]

 [[1155  562 1155  562]]]
[[[766 629 766 632]]

 [[588 606 589 602]]

 [[603   7 604   7]]

 ...

 [[697   3 697   3]]

 [[115 184 117 184]]

 [[769 611 769 613]]]
[[[ 700   13  711   13]]

 [[ 400  461  401  460]]

 [[ 225  571  225  571]]

 ...

 [[ 448  496  448  496]]

 [[1048   51 1048   51]]

 [[1139  362 1139  364]]]
[[[131 626 131 626]]

 [[191 588 191 588]]

 [[174 599 178 597]]

 ...

 [[755 570 755 570]]

 [[928 231 928 231]]

 [[354 574 354 574]]]
[[[ 659   16  659   16]]

 [[ 476   25  485   25]]

 [[ 829    8  847    8]]

 ...

 [[1088  470 1094  470]]

 [[  25  584   26  583]]

 [[1030  156 1030  156]]]
[[[637 454 637 453]]

 [[601 577 602 575]]

 [[  1 206   2 206]]

 ...

 [[760 207 760 207]]

 [[785 333 785 333]]

 [[822 241 822 241]]]
[[[ 767  672  767  675]]

 [[ 718  441  718  443]]

 [[ 396   22  409   22]]

 ...

 [[1275  690 127

[[[ 601  109  632  109]]

 [[ 255  181  260  181]]

 [[1151  185 1155  185]]

 ...

 [[ 828  223  828  223]]

 [[1232  180 1233  180]]

 [[ 998  198  998  198]]]
[[[ 593  176  600  176]]

 [[ 408  444  420  437]]

 [[ 757  660  758  669]]

 ...

 [[ 435  163  435  163]]

 [[1061  431 1061  433]]

 [[ 912   75  912   75]]]
[[[ 590  169  595  169]]

 [[ 570  107  594  107]]

 [[ 335  200  336  200]]

 ...

 [[1134  682 1134  682]]

 [[ 146  128  146  128]]

 [[1052  176 1052  176]]]
[[[ 679  106  739  106]]

 [[ 580  568  581  566]]

 [[ 735  584  735  587]]

 ...

 [[1229  181 1229  181]]

 [[ 662  211  662  211]]

 [[1267  696 1267  696]]]
[[[1051  172 1051  172]]

 [[ 654  172  658  172]]

 [[ 108  161  108  161]]

 ...

 [[ 101  139  101  139]]

 [[1066  212 1068  210]]

 [[ 636  401  636  401]]]
[[[1106  147 1108  147]]

 [[ 261  177  261  177]]

 [[ 555  691  555  690]]

 ...

 [[1238  681 1240  682]]

 [[1194   64 1196   66]]

 [[ 344  486  345  485]]]
[[[ 698  401  698  405]]

 [

[[[ 513  179  528  179]]

 [[ 709  174  711  174]]

 [[ 608  175  632  175]]

 ...

 [[1175  204 1176  204]]

 [[ 665  164  665  164]]

 [[ 619  415  619  415]]]
[[[ 115  134  115  134]]

 [[ 381  162  381  162]]

 [[ 649  161  660  161]]

 ...

 [[ 745  240  745  240]]

 [[ 130  166  131  166]]

 [[1054  651 1055  651]]]
[[[ 580  162  588  162]]

 [[ 620  161  657  161]]

 [[1023  236 1024  236]]

 ...

 [[1199  527 1201  528]]

 [[  85  151   85  151]]

 [[ 296  511  296  511]]]
[[[616  53 617  53]]

 [[541 687 542 684]]

 [[ 25 182  28 182]]

 ...

 [[107  33 108  32]]

 [[116 183 118 183]]

 [[178 684 180 684]]]
[[[ 450  164  477  164]]

 [[ 454  174  469  174]]

 [[1076  144 1077  144]]

 ...

 [[1227  486 1228  486]]

 [[ 134  148  135  149]]

 [[  51  150   51  150]]]
[[[ 573  607  573  606]]

 [[ 550  681  550  680]]

 [[ 380  170  385  170]]

 ...

 [[1128  126 1128  129]]

 [[ 707  464  708  465]]

 [[ 112  496  112  496]]]
[[[571  55 615  55]]

 [[622 168 643 168]]

 [[622  

[[[335 161 338 161]]

 [[552 153 566 153]]

 [[602 162 626 162]]

 ...

 [[744 237 744 237]]

 [[877 144 877 144]]

 [[288 140 288 140]]]
[[[ 329  159  338  159]]

 [[ 547  162  562  162]]

 [[ 711  544  711  546]]

 ...

 [[1210  173 1211  173]]

 [[ 745  199  745  199]]

 [[  32  140   33  140]]]
[[[348 157 350 157]]

 [[864 173 864 173]]

 [[794 232 794 232]]

 ...

 [[820 224 820 224]]

 [[ 76 146  76 146]]

 [[705 499 705 499]]]
[[[ 552  647  553  644]]

 [[ 574  161  583  161]]

 [[ 336  158  355  158]]

 ...

 [[ 136  177  137  177]]

 [[1222  163 1223  163]]

 [[  59  144   59  144]]]
[[[359 156 366 156]]

 [[751 159 751 159]]

 [[356 159 356 159]]

 ...

 [[769 176 769 176]]

 [[528 709 529 706]]

 [[745 667 745 667]]]
[[[483 158 502 158]]

 [[309 152 320 152]]

 [[393 150 421 150]]

 ...

 [[106 136 107 136]]

 [[113 166 115 166]]

 [[254 205 254 205]]]
[[[739 137 757 137]]

 [[831 132 838 132]]

 [[694 207 694 207]]

 ...

 [[431 178 431 178]]

 [[716 226 716 226]]

 [[818 3

[[[301 179 303 179]]

 [[462 178 482 178]]

 [[479 173 485 173]]

 ...

 [[990 120 991 119]]

 [[361 703 362 703]]

 [[230 189 230 189]]]
[[[ 741  161  741  161]]

 [[ 797  159  797  159]]

 [[ 658  164  675  164]]

 ...

 [[ 965  178  965  178]]

 [[1048  690 1048  692]]

 [[ 521  217  521  217]]]
[[[ 494  156  494  156]]

 [[ 595  168  615  168]]

 [[ 297  162  319  162]]

 ...

 [[1061  246 1062  246]]

 [[ 966  595  966  595]]

 [[ 439  212  440  213]]]
[[[ 556  627  556  626]]

 [[ 473  156  484  156]]

 [[ 761  161  761  161]]

 ...

 [[1187  195 1187  195]]

 [[ 210   10  210   12]]

 [[1119  691 1120  692]]]
[[[390 155 402 155]]

 [[344 167 345 167]]

 [[480 150 496 150]]

 ...

 [[ 12 159  12 159]]

 [[675 215 675 215]]

 [[757 254 758 253]]]
[[[597 149 599 149]]

 [[382 197 383 197]]

 [[273 164 273 164]]

 ...

 [[990 260 991 260]]

 [[603 477 604 474]]

 [[284 165 286 166]]]
[[[368 166 377 166]]

 [[330 166 330 166]]

 [[604 170 638 170]]

 ...

 [[857 133 857 133]]

 [[993

[[[ 584  131  619  131]]

 [[ 944  111  944  111]]

 [[ 627  116  629  116]]

 ...

 [[1082  223 1082  223]]

 [[ 319  483  322  481]]

 [[ 681  232  681  232]]]
[[[293 134 305 134]]

 [[339 121 364 121]]

 [[666 129 715 129]]

 ...

 [[ 82 144  82 144]]

 [[557 224 559 224]]

 [[ 81 168  82 168]]]
[[[ 322  117  359  117]]

 [[ 456  118  476  118]]

 [[  77  164   83  164]]

 ...

 [[ 202   32  202   32]]

 [[1243  188 1245  188]]

 [[1050  253 1050  253]]]
[[[627 118 627 118]]

 [[232 140 243 140]]

 [[626 198 642 198]]

 ...

 [[698 216 700 216]]

 [[747 129 747 129]]

 [[781 248 781 248]]]
[[[760 229 760 229]]

 [[491 192 495 192]]

 [[361 122 364 122]]

 ...

 [[695 245 695 245]]

 [[816 254 818 254]]

 [[301 124 303 124]]]
[[[326 129 328 129]]

 [[355 129 365 129]]

 [[497 192 498 192]]

 ...

 [[272 179 272 179]]

 [[100 623 100 623]]

 [[ 82 630  83 629]]]
[[[ 646  118  649  118]]

 [[ 374  108  382  108]]

 [[1149  174 1151  174]]

 ...

 [[  51  645   51  645]]

 [[ 884  188  

[[[482  81 516  81]]

 [[263  98 273  98]]

 [[823 551 823 551]]

 ...

 [[840 216 840 216]]

 [[439 182 439 182]]

 [[763 240 763 240]]]
[[[369  96 370  96]]

 [[436  96 478  96]]

 [[229 174 231 174]]

 ...

 [[911 262 911 265]]

 [[793 353 796 356]]

 [[  6 130   6 130]]]
[[[ 248   94  261   94]]

 [[ 696   77  721   77]]

 [[ 569  196  599  196]]

 ...

 [[1040  247 1040  247]]

 [[ 902  714  902  714]]

 [[ 252   80  253   80]]]
[[[ 352   71  391   71]]

 [[ 909   67  909   67]]

 [[1196  175 1196  175]]

 ...

 [[  21  631   22  630]]

 [[ 520  202  520  202]]

 [[ 119  572  119  572]]]
[[[ 583   80  693   80]]

 [[ 626   59  781   59]]

 [[ 676  579  676  581]]

 ...

 [[ 178  108  178  108]]

 [[1066  635 1066  635]]

 [[ 540  515  540  515]]]
[[[ 681   63  718   63]]

 [[ 506   61  516   61]]

 [[ 324   81  359   81]]

 ...

 [[1069  687 1070  687]]

 [[ 669  437  671  439]]

 [[  49   88   49   90]]]
[[[597  61 605  61]]

 [[ 66  63  71  63]]

 [[459  81 495  81]]

 ...

 [[2

[[[186  66 206  66]]

 [[707  68 726  68]]

 [[ 80 214  80 214]]

 ...

 [[ 81 229  83 229]]

 [[813  98 813  98]]

 [[ 59 189  60 189]]]
[[[512  89 607  89]]

 [[612  91 767  91]]

 [[420  65 455  65]]

 ...

 [[581 519 581 521]]

 [[943 204 943 204]]

 [[335 518 335 518]]]
[[[794  72 796  72]]

 [[227  79 228  79]]

 [[693  49 727  49]]

 ...

 [[ 60 160  61 160]]

 [[801 396 803 395]]

 [[751 216 752 216]]]
[[[ 338   54  346   54]]

 [[ 454   51  474   51]]

 [[ 642  206  678  206]]

 ...

 [[ 590  473  590  473]]

 [[ 255   65  255   65]]

 [[1031  183 1032  183]]]
[[[ 380   53  413   53]]

 [[ 646   70  700   70]]

 [[ 248   53  288   53]]

 ...

 [[1021  247 1021  247]]

 [[ 331  199  331  199]]

 [[ 557  547  557  547]]]
[[[ 788   69  790   69]]

 [[ 186   69  187   69]]

 [[ 614   69  623   69]]

 ...

 [[1016  153 1016  153]]

 [[ 610   43  612   43]]

 [[ 698  283  698  283]]]
[[[ 606   56  714   56]]

 [[ 607   58  698   58]]

 [[ 493   75  495   75]]

 ...

 [[ 991  314  99

[[[ 692  111  692  111]]

 [[ 542  572  542  571]]

 [[ 547  555  548  551]]

 ...

 [[ 653   96  653   96]]

 [[ 188   74  188   74]]

 [[1048  296 1049  296]]]
[[[ 774  249  777  249]]

 [[ 510  218  517  218]]

 [[1211  239 1211  239]]

 ...

 [[1042  283 1042  283]]

 [[1002  278 1002  278]]

 [[ 442  231  442  231]]]
[[[ 439  204  446  204]]

 [[ 846  126  846  121]]

 [[ 677  667  677  669]]

 ...

 [[1018  247 1018  247]]

 [[ 191  173  191  173]]

 [[ 532  145  535  145]]]
[[[ 292  197  293  197]]

 [[1077  183 1077  183]]

 [[ 367  196  368  196]]

 ...

 [[ 525  251  525  251]]

 [[  20  228   20  228]]

 [[ 580  667  580  668]]]
[[[619 206 656 206]]

 [[665 612 665 615]]

 [[482 206 493 206]]

 ...

 [[627 193 627 193]]

 [[742 655 742 655]]

 [[675 201 675 201]]]
[[[ 550  210  575  210]]

 [[ 919  144  919  131]]

 [[ 498  199  498  199]]

 ...

 [[ 641  255  641  255]]

 [[1109   78 1109   78]]

 [[1276  239 1276  239]]]
[[[  44  193   51  193]]

 [[ 486  203  486  203]]



[[[359 141 364 141]]

 [[240 142 257 142]]

 [[415 142 416 142]]

 ...

 [[269 147 269 147]]

 [[807 189 807 189]]

 [[120 611 120 611]]]
[[[ 671  142  685  142]]

 [[ 252  147  266  147]]

 [[ 550  152  550  152]]

 ...

 [[ 361  177  362  177]]

 [[1151   76 1153   74]]

 [[ 689  639  689  639]]]
[[[ 219  160  219  160]]

 [[1230  143 1231  143]]

 [[ 645  153  657  153]]

 ...

 [[1014  642 1015  644]]

 [[1126  146 1126  146]]

 [[ 601  153  602  153]]]
[[[ 656  136  680  136]]

 [[ 389  143  396  143]]

 [[ 591  152  593  152]]

 ...

 [[1075  247 1075  247]]

 [[  19   71   21   71]]

 [[ 776  234  776  234]]]
[[[437 155 449 155]]

 [[489 152 503 152]]

 [[566 155 606 155]]

 ...

 [[988  37 989  37]]

 [[182 128 184 128]]

 [[450 182 450 182]]]
[[[ 426  150  438  150]]

 [[ 519  162  523  162]]

 [[ 517  164  529  164]]

 ...

 [[ 933   59  933   59]]

 [[1126  131 1126  130]]

 [[ 184  137  184  137]]]
[[[1260  129 1260  129]]

 [[1108  132 1108  132]]

 [[ 433  143  459  143]]

[[[683 171 683 171]]

 [[486 171 486 171]]

 [[198 171 199 171]]

 ...

 [[227 174 231 174]]

 [[293 234 293 234]]

 [[634 627 634 631]]]
[[[266 171 266 171]]

 [[157 173 188 173]]

 [[815 169 815 148]]

 ...

 [[ 55 678  55 678]]

 [[619 567 619 567]]

 [[743 230 744 230]]]
[[[496 613 496 612]]

 [[453 162 455 162]]

 [[142 171 143 171]]

 ...

 [[124  85 124  85]]

 [[617 529 617 529]]

 [[459 231 459 231]]]
[[[283 139 291 139]]

 [[ 21 161  22 161]]

 [[253 140 280 140]]

 ...

 [[205 176 206 176]]

 [[686 206 686 201]]

 [[ 16 113  16 113]]]
[[[ 128  126  142  126]]

 [[ 485  140  495  140]]

 [[ 883  108  883  108]]

 ...

 [[1034  166 1034  165]]

 [[ 918  528  918  528]]

 [[ 947  273  947  273]]]
[[[ 567  130  577  130]]

 [[ 438  115  466  115]]

 [[ 690  125  690  125]]

 ...

 [[ 283  115  283  115]]

 [[ 392  178  393  178]]

 [[1010  269 1010  269]]]
[[[365 131 397 131]]

 [[613 112 643 112]]

 [[474 125 474 125]]

 ...

 [[368 161 368 161]]

 [[108   0 108   3]]

 [[459 6

[[[592 159 639 159]]

 [[503 134 548 134]]

 [[456 161 461 161]]

 ...

 [[232 225 232 225]]

 [[709 214 709 214]]

 [[707 218 707 218]]]
[[[ 664  140  693  140]]

 [[ 185  211  185  211]]

 [[ 588  163  623  163]]

 ...

 [[ 619  335  619  335]]

 [[ 393  260  393  260]]

 [[1259  258 1259  260]]]
[[[409 265 412 265]]

 [[341 166 383 166]]

 [[317 147 353 147]]

 ...

 [[606 564 606 564]]

 [[895 306 895 306]]

 [[721 184 722 184]]]
[[[ 275  152  282  152]]

 [[ 592  156  619  156]]

 [[ 808  112  808   98]]

 ...

 [[1104  320 1105  320]]

 [[ 214  703  219  698]]

 [[ 135  150  135  150]]]
[[[1278  186 1278  186]]

 [[ 432  150  433  150]]

 [[ 256  138  258  138]]

 ...

 [[ 719  270  719  270]]

 [[ 553  211  553  211]]

 [[ 705  196  705  197]]]
[[[555 213 555 231]]

 [[635 135 640 135]]

 [[472 135 495 135]]

 ...

 [[734 280 734 280]]

 [[909 334 909 334]]

 [[307 242 307 242]]]
[[[ 719  263  719  263]]

 [[ 355  225  356  225]]

 [[ 960  288  968  288]]

 ...

 [[ 643  253  64

[[[ 880  176  880  142]]

 [[ 800  253  800  244]]

 [[ 214   46  242   46]]

 ...

 [[1065  335 1067  335]]

 [[ 117  174  117  176]]

 [[ 989  233  989  233]]]
[[[880 206 880 193]]

 [[804 104 804  83]]

 [[545 206 551 206]]

 ...

 [[216 247 217 247]]

 [[964 342 966 342]]

 [[468 209 469 209]]]
[[[884 235 884 209]]

 [[596  51 620  51]]

 [[134 195 137 195]]

 ...

 [[358 235 358 235]]

 [[619 587 619 591]]

 [[268 224 268 224]]]
[[[229  62 267  62]]

 [[140  35 171  35]]

 [[208  32 233  32]]

 ...

 [[929 338 929 338]]

 [[256 243 257 243]]

 [[881  37 881  37]]]
[[[ 625   21  647   21]]

 [[ 131   57  169   57]]

 [[ 247   26  253   26]]

 ...

 [[1077  316 1077  316]]

 [[ 585  146  585  146]]

 [[ 417  237  417  237]]]
[[[ 300   20  301   20]]

 [[ 320   19  320   19]]

 [[ 274   49  297   49]]

 ...

 [[1041  328 1041  328]]

 [[ 552   24  552   24]]

 [[ 651  156  652  155]]]
[[[326  17 329  17]]

 [[  3 159   3 159]]

 [[552 296 554 296]]

 ...

 [[676 102 676 102]]

 [[279

[[[ 740   89  743   89]]

 [[ 677  256  683  256]]

 [[1096  337 1100  337]]

 ...

 [[1120  318 1121  318]]

 [[ 772   93  774   93]]

 [[ 353  225  353  225]]]
[[[882 290 882 255]]

 [[881 134 881 117]]

 [[806 238 806 224]]

 ...

 [[388  70 389  70]]

 [[112 172 112 172]]

 [[440 250 440 250]]]
[[[879 290 879 231]]

 [[796 309 796 296]]

 [[446  58 446  58]]

 ...

 [[273 206 273 206]]

 [[435  50 435  50]]

 [[915 238 915 233]]]
[[[ 883  129  883   15]]

 [[ 880  222  880  199]]

 [[ 802  295  806  295]]

 ...

 [[1066  238 1067  237]]

 [[ 234  243  234  243]]

 [[ 780  117  780  117]]]
[[[ 337  214  338  214]]

 [[ 614   21  614   21]]

 [[ 274  204  274  204]]

 ...

 [[1124  333 1124  333]]

 [[1058  297 1058  297]]

 [[1104  345 1104  345]]]
[[[1020  299 1022  299]]

 [[ 880   57  880    0]]

 [[ 642  246  646  246]]

 ...

 [[ 810   87  810   87]]

 [[ 767  228  767  228]]

 [[ 392   38  392   38]]]
[[[ 883  195  883  183]]

 [[ 885   80  885   33]]

 [[1096  211 1120  211]]

[[[ 215  215  216  215]]

 [[ 548  124  548  126]]

 [[ 748  321  748  321]]

 ...

 [[ 357  251  357  251]]

 [[1049  361 1050  361]]

 [[ 129  205  129  205]]]
[[[ 813  109  813   53]]

 [[1041  376 1043  376]]

 [[ 893  370  893  375]]

 ...

 [[ 361  259  361  259]]

 [[ 115  119  116  120]]

 [[ 603  241  603  241]]]
[[[672 320 678 321]]

 [[223 213 223 213]]

 [[692 324 695 324]]

 ...

 [[605 329 605 329]]

 [[653 349 654 349]]

 [[296 226 296 226]]]
[[[ 815   48  816    0]]

 [[ 412  274  421  275]]

 [[ 889  124  889  113]]

 ...

 [[1086  241 1086  241]]

 [[ 417  252  418  252]]

 [[ 742  366  742  366]]]
[[[ 964  303  967  303]]

 [[ 605  306  611  306]]

 [[1065  365 1068  365]]

 ...

 [[ 791  305  791  305]]

 [[ 123  195  123  195]]

 [[ 653  708  653  708]]]
[[[ 565  202  566  212]]

 [[ 641  332  654  332]]

 [[ 816  144  816  127]]

 ...

 [[1170  236 1172  235]]

 [[1266  261 1268  261]]

 [[1053  317 1053  317]]]
[[[ 818    9  818    0]]

 [[ 611  300  619  300]]



[[[797 252 798 252]]

 [[546 253 551 253]]

 [[596 245 632 245]]

 ...

 [[115 157 115 157]]

 [[254 195 254 195]]

 [[629 553 629 553]]]
[[[ 676  336  679  335]]

 [[ 881  300  881  300]]

 [[ 643  241  702  241]]

 ...

 [[1020  360 1021  360]]

 [[ 529  317  529  317]]

 [[1039  355 1039  355]]]
[[[ 528  242  567  242]]

 [[ 889  286  889  303]]

 [[ 414  247  418  248]]

 ...

 [[ 975  336  975  336]]

 [[1249  199 1249  199]]

 [[ 276  184  276  184]]]
[[[1176  236 1180  236]]

 [[1133  277 1133  277]]

 [[1247  260 1249  260]]

 ...

 [[ 995  342  996  342]]

 [[ 378  235  379  235]]

 [[ 250  177  250  177]]]
[[[408 239 410 239]]

 [[401 236 404 236]]

 [[593 286 593 286]]

 ...

 [[930 280 930 280]]

 [[590 323 590 323]]

 [[575 276 575 276]]]
[[[1142  319 1150  320]]

 [[ 891  256  891  256]]

 [[ 722  251  722  251]]

 ...

 [[ 164  203  164  203]]

 [[1086  296 1087  296]]

 [[ 654  204  654  204]]]
[[[1115  305 1117  305]]

 [[ 968  295  971  295]]

 [[ 384  252  386  252]]

[[[ 595  315  599  315]]

 [[1137  314 1137  314]]

 [[ 992  292  995  292]]

 ...

 [[ 715  314  715  314]]

 [[ 774   20  778   20]]

 [[ 802  317  802  317]]]
[[[482 133 521 133]]

 [[571 310 582 310]]

 [[991 316 996 316]]

 ...

 [[636 290 637 290]]

 [[632 335 632 335]]

 [[936 240 936 240]]]
[[[ 919   98  919  127]]

 [[ 701  262  706  262]]

 [[1169  269 1171  269]]

 ...

 [[1182  317 1183  317]]

 [[ 526  622  526  621]]

 [[ 175  118  175  118]]]
[[[ 480  126  546  126]]

 [[ 557  128  695  128]]

 [[1164  318 1164  318]]

 ...

 [[ 925  215  925  215]]

 [[1041  348 1043  348]]

 [[ 888  292  888  292]]]
[[[595 126 655 126]]

 [[595 124 655 124]]

 [[892  32 892  19]]

 ...

 [[805 132 805 132]]

 [[986   7 986   7]]

 [[620 325 621 325]]]
[[[650 119 703 119]]

 [[477 117 518 117]]

 [[327 210 327 210]]

 ...

 [[317 240 317 240]]

 [[595   8 595  16]]

 [[968  94 968  94]]]
[[[   6  199    6  199]]

 [[ 301  227  302  227]]

 [[1089  343 1089  343]]

 ...

 [[ 157  235  15

[[[1076  272 1080  272]]

 [[ 586  259  612  259]]

 [[ 664  194  707  194]]

 ...

 [[ 741  218  741  218]]

 [[ 390  226  390  226]]

 [[1011  326 1011  326]]]
[[[1141  272 1143  272]]

 [[ 747  280  749  280]]

 [[1011  307 1011  307]]

 ...

 [[ 215  156  215  156]]

 [[ 155   80  155   80]]

 [[ 615  208  615  208]]]
[[[1022  204 1022  204]]

 [[ 646  191  674  191]]

 [[ 880  264  880  185]]

 ...

 [[ 649  290  650  291]]

 [[1021  274 1021  274]]

 [[ 541  572  541  572]]]
[[[1159  313 1164  313]]

 [[ 804  234  804  210]]

 [[ 572  266  575  267]]

 ...

 [[ 295  226  295  226]]

 [[ 260  171  260  171]]

 [[ 503  275  503  275]]]
[[[ 877   94  877    0]]

 [[ 568  267  585  268]]

 [[ 611  264  615  264]]

 ...

 [[ 797  326  800  325]]

 [[ 226  183  227  183]]

 [[1024  235 1024  235]]]
[[[1160  225 1172  225]]

 [[1264  286 1265  286]]

 [[ 810  144  810  118]]

 ...

 [[ 682  321  682  321]]

 [[ 181   99  182  100]]

 [[ 875  243  875  243]]]
[[[ 805  264  805  249]]

 [

[[[1087  361 1087  361]]

 [[ 512  252  516  252]]

 [[ 616  251  618  251]]

 ...

 [[1146  378 1146  378]]

 [[ 603  171  603  171]]

 [[ 741  250  741  250]]]
[[[ 704  246  730  246]]

 [[ 938  296  946  296]]

 [[ 699  306  705  306]]

 ...

 [[ 244  257  244  257]]

 [[1127  364 1127  364]]

 [[ 238  178  239  178]]]
[[[1148  282 1148  282]]

 [[ 476  237  503  237]]

 [[ 935  331  939  331]]

 ...

 [[ 687  345  687  345]]

 [[ 910  364  910  364]]

 [[1095  280 1095  280]]]
[[[1211  276 1211  276]]

 [[ 912  286  922  286]]

 [[ 541  231  584  231]]

 ...

 [[ 286  197  287  197]]

 [[ 652  304  652  304]]

 [[ 271  205  272  205]]]
[[[1062  325 1064  325]]

 [[ 179  170  182  170]]

 [[ 964  288  965  288]]

 ...

 [[ 263  219  263  219]]

 [[ 352  233  353  233]]

 [[ 639  292  639  292]]]
[[[813 227 813 227]]

 [[693 228 721 228]]

 [[686 225 725 225]]

 ...

 [[171 177 171 177]]

 [[908 311 908 311]]

 [[656 335 656 335]]]
[[[1166  267 1167  267]]

 [[ 267  220  268  220]]



[[[962  68 962  96]]

 [[442 101 442 101]]

 [[866 176 866 176]]

 ...

 [[597 319 597 319]]

 [[726 204 726 204]]

 [[966 290 966 290]]]
[[[ 102   42  102   42]]

 [[ 976  177  976  207]]

 [[ 978  368  978  369]]

 ...

 [[1172  625 1172  625]]

 [[ 139    7  139    7]]

 [[1153  657 1154  658]]]
[[[ 749  165  749  165]]

 [[ 120   43  120   43]]

 [[ 148  548  148  548]]

 ...

 [[ 951  121  951  121]]

 [[1088  680 1088  680]]

 [[ 561  322  561  322]]]
[[[ 974   36  974   59]]

 [[1170  439 1171  439]]

 [[ 331   80  331   80]]

 ...

 [[ 190   88  190   88]]

 [[ 482  673  482  673]]

 [[1007  604 1007  604]]]
[[[ 828  166  828  195]]

 [[  70   20   72   21]]

 [[1103  363 1107  364]]

 ...

 [[ 965  473  965  473]]

 [[ 162   57  162   57]]

 [[  90  583   92  582]]]
[[[ 186  530  187  529]]

 [[ 560  160  560  160]]

 [[1210  379 1210  379]]

 ...

 [[ 185   30  185   30]]

 [[1030  188 1030  188]]

 [[ 956  430  956  430]]]
[[[ 987  217  987  218]]

 [[ 977  319  979  319]]



[[[ 571  668  576  668]]

 [[1077  422 1077  422]]

 [[1011  345 1011  345]]

 ...

 [[ 713   90  713   90]]

 [[1211  578 1211  578]]

 [[ 610  599  610  599]]]
[[[ 397  528  399  528]]

 [[ 296  374  298  373]]

 [[ 662  506  662  506]]

 ...

 [[1183  489 1183  489]]

 [[1202  389 1203  390]]

 [[ 540  658  542  658]]]
[[[ 516  564  516  564]]

 [[ 601  561  621  561]]

 [[ 830  373  836  372]]

 ...

 [[  92  500   93  499]]

 [[1076  434 1076  434]]

 [[ 357  493  357  493]]]
[[[ 598  486  599  485]]

 [[ 985  194  985  194]]

 [[1009  335 1009  335]]

 ...

 [[1006  257 1006  257]]

 [[ 527  520  528  517]]

 [[ 358  361  359  361]]]
[[[ 680  506  694  506]]

 [[ 272  592  272  592]]

 [[ 184  519  199  519]]

 ...

 [[1187  318 1187  318]]

 [[1063   10 1063   10]]

 [[ 379  331  381  330]]]
[[[ 755  504  755  504]]

 [[1260  439 1260  439]]

 [[1229  521 1232  521]]

 ...

 [[ 300  564  300  564]]

 [[ 883  252  883  251]]

 [[1266  331 1266  330]]]
[[[ 602  675  621  675]]

 [

[[[ 326  451  326  451]]

 [[ 349  437  350  436]]

 [[ 571  522  577  522]]

 ...

 [[1101  453 1101  453]]

 [[ 762  280  763  279]]

 [[1087  295 1087  295]]]
[[[ 153  689  154  688]]

 [[ 853  145  853  145]]

 [[ 289  571  294  566]]

 ...

 [[ 833  677  833  677]]

 [[ 187  181  187  181]]

 [[1112  455 1113  454]]]
[[[ 640  654  648  654]]

 [[1046  256 1047  256]]

 [[ 688  519  691  519]]

 ...

 [[ 513  102  513  102]]

 [[1254  132 1254  132]]

 [[ 128  612  128  612]]]
[[[1206   66 1207   51]]

 [[ 397   26  397   26]]

 [[ 153  536  153  536]]

 ...

 [[  18  354   18  354]]

 [[1269  250 1269  250]]

 [[ 185  509  185  509]]]
[[[ 861  151  862  150]]

 [[ 241  541  250  541]]

 [[ 570  683  579  683]]

 ...

 [[ 916  154  916  154]]

 [[1265   98 1265   98]]

 [[1143  329 1143  329]]]
[[[ 670  662  680  662]]

 [[1041  265 1041  265]]

 [[  94  261   95  261]]

 ...

 [[1019  325 1019  325]]

 [[ 984  380  985  379]]

 [[ 860  156  860  156]]]
[[[ 235  498  238  496]]

 [

[[[ 294  480  294  480]]

 [[ 533  685  533  683]]

 [[ 327  460  327  460]]

 ...

 [[1227   61 1227   60]]

 [[ 640  628  642  628]]

 [[ 593  603  594  602]]]
[[[ 981  163  984  163]]

 [[ 719  272  719  272]]

 [[1115  173 1118  173]]

 ...

 [[   2  640    2  640]]

 [[1020  361 1022  361]]

 [[1135  502 1135  502]]]
[[[1207   66 1207   62]]

 [[ 344  441  344  441]]

 [[ 437   62  437   62]]

 ...

 [[ 576   98  576   98]]

 [[1072  713 1074  713]]

 [[ 367   93  368   93]]]
[[[ 196  603  196  603]]

 [[ 153  551  155  550]]

 [[ 760  141  760  141]]

 ...

 [[1122  226 1122  226]]

 [[ 359   71  359   71]]

 [[1176  200 1176  200]]]
[[[ 162  653  176  653]]

 [[1015  348 1016  348]]

 [[ 303   31  305   31]]

 ...

 [[ 496   70  496   70]]

 [[ 866  158  866  158]]

 [[ 821  137  821  137]]]
[[[ 341  439  342  438]]

 [[ 641  641  641  641]]

 [[1155   89 1155   81]]

 ...

 [[ 373  625  373  625]]

 [[ 906  323  906  323]]

 [[ 856  288  858  288]]]


error: OpenCV(3.4.1) C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\imgproc\src\color.cpp:11214: error: (-215) (scn == 3 || scn == 4) && (depth == 0 || depth == 5) in function cv::cvtColor
